// const cities = {
//   // --- المحافظات الرئيسية ---
//   'Cairo': ['القاهرة', 'Cairo', 'القاهره', 'Cahira'],
//   'Giza': ['الجيزة', 'Giza','الجيزه'],
//   'Alexandria': ['الإسكندرية', 'Alex', 'Alexandria', 'اسكندريه', 'الإسكندريه'],
//   'Kafr ash Shaykh': ['كفرالشيخ', 'Kafr El Sheikh', 'كفر الشيخ'],
//   'Beheira': ['البحيرة', 'Beheira', 'البحيره'],
//   'Dakahlia': ['الدقهلية', 'Dakahlia', 'الدقهلية'],
//   'Sharqia': ['الشرقية', 'Sharqia', 'الشرقيه'],
//   'Gharbia': ['الغربية', 'Gharbia', 'الغربيه'],
//   'Monufia': ['المنوفية', 'Monufia', 'المنوفيه'],
//   'Qalyubia': ['القليوبية', 'Qalyubia', 'القليوبيه'],
//   'Damietta': ['دمياط', 'Damietta', 'دمياط'],
//   'Port Said': ['بورسعيد', 'Port Said', 'بور سعيد'],
//   'Suez': ['السويس', 'Suez', 'السويس'],
//   'Ismailia': ['الإسماعيلية', 'Ismailia', 'الاسماعيليه'],
//   'Faiyum': ['الفيوم', 'Faiyum', 'الفيووم'],
//   'Beni Suef': ['بني سويف', 'Beni Suef', 'بني سويف'],
//   'Minya': ['المنيا', 'Minya', 'المنيا'],
//   'Asyut': ['أسيوط', 'Asyut', 'اسيوط'],
//   'Sohag': ['سوهاج', 'Sohag', 'سوهاج'],
//   'Qena': ['قنا', 'Qena', 'قنا'],
//   'Luxor': ['الأقصر', 'Luxor', 'الأقصر'],
//   'Aswan': ['أسوان', 'Aswan', 'اسوان'],
//   'Marsa Matruh': ['مرسى مطروح', 'Marsa Matruh', 'مرسي مطروح'],
//   'North Sinai': ['شمال سيناء', 'North Sinai', 'شمال سيناء'],
//   'South Sinai': ['جنوب سيناء', 'South Sinai', 'جنوب سيناء'],
//   'Red Sea': ['البحر الأحمر', 'Red Sea', 'البحر الاحمر'],
//   'New Valley': ['الوادي الجديد', 'New Valley', 'الوادي الجديد'],

//   // --- مراكز كفر الشيخ ---
//   'Desouk': ['دسوق', 'Desouk'],
//   'Metoubes': ['مطوبس', 'Metoubes'],
//   'Sīdī Sālim': ['سيدي سالم', 'Sidi Salem'],
//   'Bella': ['بيلا', 'Bella'],
//   'Fuwwah': ['فوه', 'Fuwwah'],
//   'Qallin': ['قلين', 'Qallin'],
//   'Burullus': ['البرلس', 'Burullus'],
//   'Hamol': ['الحامول', 'Hamol'],
//   'Riadh': ['الرياض', 'Riadh'],

//   // --- مراكز البحيرة ---
//   'Damanhur': ['دمنهور', 'Damanhur'],
//   'Kafr El Dawwar': ['كفر الدوار', 'Kafr El Dawwar'],
//   'Abou Homs': ['أبو حمص', 'Abou Homs'],
//   'Etay El Barud': ['إيتاي البارود', 'Etay El Barud'],
//   'Housh Eissa': ['حوش عيسى', 'Housh Eissa'],
//   'Kom Hamada': ['كوم حمادة', 'Kom Hamada'],
//   'Shubrakhit': ['شبراخيت', 'Shubrakhit'],
//   'Wadi El Natrun': ['وادي النطرون', 'Wadi El Natrun'],
//   'Edku': ['إدكو', 'Edku'],
//   'Rashid': ['رشيد', 'Rashid'],

//   // --- مراكز الغربية ---
//   'Tanta': ['طنطا', 'Tanta'],
//   'Al Mahalla': ['المحلة الكبرى', 'Al Mahalla'],
//   'Kafr El Zayat': ['كفر الزيات', 'Kafr El Zayat'],
//   'Zefta': ['زفتى', 'Zefta'],
//   'Basyoun': ['بسيون', 'Basyoun'],
//   'Qutour': ['قطور', 'Qutour'],
//   'Samannoud': ['سمنود', 'Samannoud'],

//   // --- مراكز الدقهلية ---
//   'Mansoura': ['المنصورة', 'Mansoura'],
//   'Talkha': ['طلخا', 'Talkha'],
//   'Mit Ghamr': ['ميت غمر', 'Mit Ghamr'],
//   'Aga': ['أجا', 'Aga'],
//   'Dekernes': ['دكرنس', 'Dekernes'],
//   'Manzala': ['المنزلة', 'Manzala'],
//   'Belqas': ['بلقاس', 'Belqas'],
//   'Sherbin': ['شربين', 'Sherbin'],
//   'Tamiya': ['تمي الأمديد', 'Tamiya'],

//   // --- مراكز الشرقية ---
//   'Zagazig': ['الزقازيق', 'Zagazig'],
//   '10th of Ramadan': ['العاشر من رمضان', '10th of Ramadan'],
//   'Abu Kabir': ['أبو كبير', 'Abu Kabir'],
//   'Kafr Saqr': ['كفر صقر', 'Kafr Saqr'],
//   'Faqus': ['فاقوس', 'Faqus'],
//   'Minya Al Qamh': ['منيا القمح', 'Minya Al Qamh'],
//   'Belbeis': ['بلبيس', 'Belbeis'],
//   'Husseiniya': ['الحسينية', 'Husseiniya'],

//   // --- الدلتا & مدن أخرى ---
//   'Shibin El Kom': ['شبين الكوم', 'Shibin El Kom'],
//   'Shebin El Qanater': ['شبين القناطر', 'Shebin El Qanater'],
//   'Benha': ['بنها', 'Benha'],
//   'Quesna': ['قويسنا', 'Quesna'],
//   'Ashmoun': ['أشمون', 'Ashmoun'],
//   'Menouf': ['منوف', 'Menouf'],

//   // --- مدن سيناء ---
//   'Arish': ['العريش', 'Arish'],
//   'Rafah': ['رفح', 'Rafah'],
//   'Nakhl': ['نخل', 'Nakhl'],
//   'Tor': ['الطور', 'Tor'],
//   'Sharm El Sheikh': ['شرم الشيخ', 'Sharm El Sheikh'],
//   'Dahab': ['دهب', 'Dahab'],
//   'Nuweiba': ['نويبع', 'Nuweiba'],
//   'Taba': ['طابا', 'Taba'],

//   // --- مدن القناة ---
//   'Ismailia City': ['الإسماعيلية', 'Ismailia City'],
//   'Port Said City': ['بورسعيد', 'Port Said City'],
//   'Suez City': ['السويس', 'Suez City'],

//   // --- مدن الصعيد ---
//   'Beni Suef City': ['بني سويف', 'Beni Suef City'],
//   'Minya City': ['المنيا', 'Minya City'],
//   'Asyut City': ['أسيوط', 'Asyut City'],
//   'Sohag City': ['سوهاج', 'Sohag City'],
//   'Qena City': ['قنا', 'Qena City'],
//   'Luxor City': ['الأقصر', 'Luxor City'],
//   'Aswan City': ['أسوان', 'Aswan City'],

//   // --- Capitals of the World ---
//   'Washington': ['واشنطن', 'Washington'],
//   'London': ['لندن', 'London'],
//   'Paris': ['باريس', 'Paris'],
//   'Berlin': ['برلين', 'Berlin'],
//   'Rome': ['روما', 'Rome'],
//   'Madrid': ['مدريد', 'Madrid'],
//   'Lisbon': ['لشبونة', 'Lisbon'],
//   'Ottawa': ['أوتاوا', 'Ottawa'],
//   'Moscow': ['موسكو', 'Moscow'],
//   'Beijing': ['بكين', 'Beijing'],
//   'Tokyo': ['طوكيو', 'Tokyo'],
//   'Seoul': ['سيول', 'Seoul'],
//   'New Delhi': ['نيودلهي', 'New Delhi'],
//   'Islamabad': ['إسلام آباد', 'Islamabad'],
//   'Tehran': ['طهران', 'Tehran'],
//   'Riyadh': ['الرياض', 'Riyadh'],
//   'Abu Dhabi': ['أبوظبي', 'Abu Dhabi'],
//   'Doha': ['الدوحة', 'Doha'],
//   'Manama': ['المنامة', 'Manama'],
//   'Kuwait City': ['مدينة الكويت', 'Kuwait City'],
//   'Muscat': ['مسقط', 'Muscat'],
//   'Ankara': ['أنقرة', 'Ankara'],
//   'Athens': ['أثينا', 'Athens'],
//   'Brussels': ['بروكسل', 'Brussels'],
//   'Amsterdam': ['أمستردام', 'Amsterdam'],
//   'Vienna': ['فيينا', 'Vienna'],
//   'Bern': ['برن', 'Bern'],
//   'Stockholm': ['ستوكهولم', 'Stockholm'],
//   'Oslo': ['أوسلو', 'Oslo'],
//   'Copenhagen': ['كوبنهاغن', 'Copenhagen'],
//   'Helsinki': ['هلسنكي', 'Helsinki'],
//   'Dublin': ['دبلن', 'Dublin'],
//   'Reykjavik': ['ريكيافيك', 'Reykjavik'],
//   'Khartoum': ['الخرطوم', 'Khartoum'],
//   'Tunis': ['تونس', 'Tunis'],
//   'Algiers': ['الجزائر', 'Algiers'],
//   'Rabat': ['الرباط', 'Rabat'],
//   'Tripoli': ['طرابلس', 'Tripoli'],
//   'Nairobi': ['نيروبي', 'Nairobi'],
//   'Pretoria': ['بريتوريا', 'Pretoria'],
//   'Canberra': ['كانبرا', 'Canberra'],
//   'Wellington': ['ويلينغتون', 'Wellington'],
//   'Brasilia': ['برازيليا', 'Brasilia'],
//   'Buenos Aires': ['بوينس آيرس', 'Buenos Aires'],
//   'Santiago': ['سانتياغو', 'Santiago'],
//   'Lima': ['ليما', 'Lima'],
//   'Caracas': ['كاراكاس', 'Caracas'],
//   'Bogota': ['بوغوتا', 'Bogota'],
//   'Havana': ['هافانا', 'Havana'],
//   'Mexico City': ['مكسيكو سيتي', 'Mexico City']
// };

// export default cities;


const cities = {
  // --- المحافظات الرئيسية ---
  'Cairo': { ar: 'القاهرة', en: 'Cairo' },
  'Giza': { ar: 'الجيزة', en: 'Giza' },
  'Alexandria': { ar: 'الإسكندرية', en: 'Alexandria' },
  'Kafr ash Shaykh': { ar: 'كفر الشيخ', en: 'Kafr ash Shaykh' },
  'Beheira': { ar: 'البحيرة', en: 'Beheira' },
  'Dakahlia': { ar: 'الدقهلية', en: 'Dakahlia' },
  'Sharqia': { ar: 'الشرقية', en: 'Sharqia' },
  'Gharbia': { ar: 'الغربية', en: 'Gharbia' },
  'Monufia': { ar: 'المنوفية', en: 'Monufia' },
  'Qalyubia': { ar: 'القليوبية', en: 'Qalyubia' },
  'Damietta': { ar: 'دمياط', en: 'Damietta' },
  'Port Said': { ar: 'بورسعيد', en: 'Port Said' },
  'Suez': { ar: 'السويس', en: 'Suez' },
  'Al Ismailiya': { ar: 'الإسماعيلية', en: 'Ismailia' },
  'Faiyum': { ar: 'الفيوم', en: 'Faiyum' },
  'Beni Suef': { ar: 'بني سويف', en: 'Beni Suef' },
  'Minya': { ar: 'المنيا', en: 'Minya' },
  'Asyut': { ar: 'أسيوط', en: 'Asyut' },
  'Sohag': { ar: 'سوهاج', en: 'Sohag' },
  'Qena': { ar: 'قنا', en: 'Qena' },
  'Luxor': { ar: 'الأقصر', en: 'Luxor' },
  'Aswan': { ar: 'أسوان', en: 'Aswan' },
  'Marsa Matruh': { ar: 'مرسى مطروح', en: 'Marsa Matruh' },
  'North Sinai': { ar: 'شمال سيناء', en: 'North Sinai' },
  'South Sinai': { ar: 'جنوب سيناء', en: 'South Sinai' },
  'Red Sea': { ar: 'البحر الأحمر', en: 'Red Sea' },
  'New Valley': { ar: 'الوادي الجديد', en: 'New Valley' },

  // --- مراكز كفر الشيخ ---
  'Disūq': { ar: 'دسوق', en: 'Desouk' },
  'Mutubis': { ar: 'مطوبس', en: 'Metoubes' },
  'Sīdī Sālim': { ar: 'سيدي سالم', en: 'Sidi Salim' },
  'Biala': { ar: 'بيلا', en: 'Biala' },
  'Fuwwah': { ar: 'فوه', en: 'Fuwwah' },
  'Qallin': { ar: 'قلين', en: 'Qallin' },
  'Burullus': { ar: 'البرلس', en: 'Burullus' },
  'Hamol': { ar: 'الحامول', en: 'Hamol' },
  'Riadh': { ar: 'الرياض', en: 'Riadh' },

  // --- مراكز البحيرة ---
  'Damanhur': { ar: 'دمنهور', en: 'Damanhur' },
  'Kafr El Dawwar': { ar: 'كفر الدوار', en: 'Kafr El Dawwar' },
  'Abou Homs': { ar: 'أبو حمص', en: 'Abou Homs' },
  'Etay El Barud': { ar: 'إيتاي البارود', en: 'Etay El Barud' },
  'Housh Eissa': { ar: 'حوش عيسى', en: 'Housh Eissa' },
  'Kom Hamada': { ar: 'كوم حمادة', en: 'Kom Hamada' },
  'Shubrakhit': { ar: 'شبراخيت', en: 'Shubrakhit' },
  'Wadi El Natrun': { ar: 'وادي النطرون', en: 'Wadi El Natrun' },
  'Edku': { ar: 'إدكو', en: 'Edku' },
  'Rashid': { ar: 'رشيد', en: 'Rashid' },

  // --- مراكز الغربية ---
  'Tanta': { ar: 'طنطا', en: 'Tanta' },
  'Al Mahalla': { ar: 'المحلة الكبرى', en: 'Al Mahalla' },
  'Kafr El Zayat': { ar: 'كفر الزيات', en: 'Kafr El Zayat' },
  'Zefta': { ar: 'زفتى', en: 'Zefta' },
  'Basyoun': { ar: 'بسيون', en: 'Basyoun' },
  'Qutour': { ar: 'قطور', en: 'Qutour' },
  'Samannoud': { ar: 'سمنود', en: 'Samannoud' },

  // --- مراكز الدقهلية ---
  'Mansoura': { ar: 'المنصورة', en: 'Mansoura' },
  'Talkha': { ar: 'طلخا', en: 'Talkha' },
  'Mit Ghamr': { ar: 'ميت غمر', en: 'Mit Ghamr' },
  'Aga': { ar: 'أجا', en: 'Aga' },
  'Dekernes': { ar: 'دكرنس', en: 'Dekernes' },
  'Manzala': { ar: 'المنزلة', en: 'Manzala' },
  'Belqas': { ar: 'بلقاس', en: 'Belqas' },
  'Sherbin': { ar: 'شربين', en: 'Sherbin' },
  'Tamiya': { ar: 'تمي الأمديد', en: 'Tamiya' },

  // --- مراكز الشرقية ---
  'Zagazig': { ar: 'الزقازيق', en: 'Zagazig' },
  '10th of Ramadan': { ar: 'العاشر من رمضان', en: '10th of Ramadan' },
  'Abu Kabir': { ar: 'أبو كبير', en: 'Abu Kabir' },
  'Kafr Saqr': { ar: 'كفر صقر', en: 'Kafr Saqr' },
  'Faqus': { ar: 'فاقوس', en: 'Faqus' },
  'Minya Al Qamh': { ar: 'منيا القمح', en: 'Minya Al Qamh' },
  'Belbeis': { ar: 'بلبيس', en: 'Belbeis' },
  'Husseiniya': { ar: 'الحسينية', en: 'Husseiniya' },

  // --- الدلتا & مدن أخرى ---
  'Shibin El Kom': { ar: 'شبين الكوم', en: 'Shibin El Kom' },
  'Shebin El Qanater': { ar: 'شبين القناطر', en: 'Shebin El Qanater' },
  'Benha': { ar: 'بنها', en: 'Benha' },
  'Quesna': { ar: 'قويسنا', en: 'Quesna' },
  'Ashmoun': { ar: 'أشمون', en: 'Ashmoun' },
  'Menouf': { ar: 'منوف', en: 'Menouf' },

  // --- مدن سيناء ---
  'Arish': { ar: 'العريش', en: 'Arish' },
  'Rafah': { ar: 'رفح', en: 'Rafah' },
  'Nakhl': { ar: 'نخل', en: 'Nakhl' },
  'Tor': { ar: 'الطور', en: 'Tor' },
  'Sharm El Sheikh': { ar: 'شرم الشيخ', en: 'Sharm El Sheikh' },
  'Dahab': { ar: 'دهب', en: 'Dahab' },
  'Nuweiba': { ar: 'نويبع', en: 'Nuweiba' },
  'Taba': { ar: 'طابا', en: 'Taba' },

  // --- عواصم العالم ---
  'Washington': { ar: 'واشنطن', en: 'Washington' },
  'London': { ar: 'لندن', en: 'London' },
  'Paris': { ar: 'باريس', en: 'Paris' },
  'Berlin': { ar: 'برلين', en: 'Berlin' },
  'Rome': { ar: 'روما', en: 'Rome' },
  'Madrid': { ar: 'مدريد', en: 'Madrid' },
  'Lisbon': { ar: 'لشبونة', en: 'Lisbon' },
  'Ottawa': { ar: 'أوتاوا', en: 'Ottawa' },
  'Moscow': { ar: 'موسكو', en: 'Moscow' },
  'Beijing': { ar: 'بكين', en: 'Beijing' },
  'Tokyo': { ar: 'طوكيو', en: 'Tokyo' },
  'Seoul': { ar: 'سيول', en: 'Seoul' },
  'New Delhi': { ar: 'نيودلهي', en: 'New Delhi' },
  'Islamabad': { ar: 'إسلام آباد', en: 'Islamabad' },
  'Tehran': { ar: 'طهران', en: 'Tehran' },
  'Riyadh': { ar: 'الرياض', en: 'Riyadh' },
  'Abu Dhabi': { ar: 'أبوظبي', en: 'Abu Dhabi' },
  'Doha': { ar: 'الدوحة', en: 'Doha' },
  'Manama': { ar: 'المنامة', en: 'Manama' },
  'Kuwait City': { ar: 'مدينة الكويت', en: 'Kuwait City' },
  'Muscat': { ar: 'مسقط', en: 'Muscat' },
  'Ankara': { ar: 'أنقرة', en: 'Ankara' },
  'Athens': { ar: 'أثينا', en: 'Athens' },
  'Brussels': { ar: 'بروكسل', en: 'Brussels' },
  'Amsterdam': { ar: 'أمستردام', en: 'Amsterdam' },
  'Vienna': { ar: 'فيينا', en: 'Vienna' },
  'Bern': { ar: 'برن', en: 'Bern' },
  'Stockholm': { ar: 'ستوكهولم', en: 'Stockholm' },
  'Oslo': { ar: 'أوسلو', en: 'Oslo' },
  'Copenhagen': { ar: 'كوبنهاغن', en: 'Copenhagen' },
  'Helsinki': { ar: 'هلسنكي', en: 'Helsinki' },
  'Dublin': { ar: 'دبلن', en: 'Dublin' },
  'Reykjavik': { ar: 'ريكيافيك', en: 'Reykjavik' },
  'Khartoum': { ar: 'الخرطوم', en: 'Khartoum' },
  'Tunis': { ar: 'تونس', en: 'Tunis' },
  'Algiers': { ar: 'الجزائر', en: 'Algiers' },
  'Rabat': { ar: 'الرباط', en: 'Rabat' },
  'Tripoli': { ar: 'طرابلس', en: 'Tripoli' },
  'Nairobi': { ar: 'نيروبي', en: 'Nairobi' },
  'Pretoria': { ar: 'بريتوريا', en: 'Pretoria' },
  'Canberra': { ar: 'كانبرا', en: 'Canberra' },
  'Wellington': { ar: 'ويلينغتون', en: 'Wellington' },
  'Brasilia': { ar: 'برازيليا', en: 'Brasilia' },
  'Jerusalem': { ar: 'القدس', en: 'Jerusalem' },
  'Buenos Aires': { ar: 'بوينس آيرس', en: 'Buenos Aires' },
  'Santiago': { ar: 'سانتياغو', en: 'Santiago' },
  'Lima': { ar: 'ليما', en: 'Lima' },
  'Caracas': { ar: 'كاراكاس', en: 'Caracas' },
  'Bogota': { ar: 'بوغوتا', en: 'Bogota' },
  'Havana': { ar: 'هافانا', en: 'Havana' },
  'Mexico City': { ar: 'مكسيكو سيتي', en: 'Mexico City' }
};

// قاموس للبحث: يربط الأسماء العربية والإنجليزية بالمفتاح الرئيسي
const cityAliases = {
  // Cairo
  'القاهرة': 'Cairo',
  'القاهره': 'Cairo',
  'قاهرة': 'Cairo',
  'cairo': 'Cairo',
  
  // Giza
  'الجيزة': 'Giza',
  'الجيزه': 'Giza',
  'جيزة': 'Giza',
  'giza': 'Giza',
  
  // Alexandria
  'الإسكندرية': 'Alexandria',
  'الاسكندرية': 'Alexandria',
  'اسكندرية': 'Alexandria',
  'إسكندرية': 'Alexandria',
  'اسكندريه': 'Alexandria',
  'الإسكندريه': 'Alexandria',
  'alex': 'Alexandria',
  'alexandria': 'Alexandria',
  
  // Kafr ash Shaykh
  'كفر الشيخ': 'Kafr ash Shaykh',
  'كفرالشيخ': 'Kafr ash Shaykh',
  'kafr el sheikh': 'Kafr ash Shaykh',
  'kafr ash shaykh': 'Kafr ash Shaykh',
  
  // Sidi Salem
  'سيدي سالم': 'Sīdī Sālim',
  'sidi salem': 'Sīdī Sālim',
  
  // Damanhur
  'دمنهور': 'Damanhur',
  'damanhur': 'Damanhur',
  
  // Tanta
  'طنطا': 'Tanta',
  'tanta': 'Tanta',
  
  // Mansoura
  'المنصورة': 'Mansoura',
  'المنصوره': 'Mansoura',
  'منصورة': 'Mansoura',
  'منصوره': 'Mansoura',
  'mansoura': 'Mansoura',
  
  // يمكنك إضافة المزيد من الأسماء البديلة هنا
};

export { cityAliases };
export default cities;