const countries = {
  AF: { ar: "أفغانستان", en: "Afghanistan" },
  AL: { ar: "ألبانيا", en: "Albania" },
  DZ: { ar: "الجزائر", en: "Algeria" },
  AD: { ar: "أندورا", en: "Andorra" },
  AO: { ar: "أنغولا", en: "Angola" },
  AR: { ar: "الأرجنتين", en: "Argentina" },
  AM: { ar: "أرمينيا", en: "Armenia" },
  AU: { ar: "أستراليا", en: "Australia" },
  AT: { ar: "النمسا", en: "Austria" },
  AZ: { ar: "أذربيجان", en: "Azerbaijan" },

  BH: { ar: "البحرين", en: "Bahrain" },
  BD: { ar: "بنغلاديش", en: "Bangladesh" },
  BY: { ar: "بيلاروسيا", en: "Belarus" },
  BE: { ar: "بلجيكا", en: "Belgium" },
  BZ: { ar: "بليز", en: "Belize" },
  BJ: { ar: "بنين", en: "Benin" },
  BT: { ar: "بوتان", en: "Bhutan" },
  BO: { ar: "بوليفيا", en: "Bolivia" },
  BA: { ar: "البوسنة والهرسك", en: "Bosnia and Herzegovina" },
  BW: { ar: "بوتسوانا", en: "Botswana" },

  BR: { ar: "البرازيل", en: "Brazil" },
  BG: { ar: "بلغاريا", en: "Bulgaria" },
  BF: { ar: "بوركينا فاسو", en: "Burkina Faso" },
  BI: { ar: "بوروندي", en: "Burundi" },

  KH: { ar: "كمبوديا", en: "Cambodia" },
  CM: { ar: "الكاميرون", en: "Cameroon" },
  CA: { ar: "كندا", en: "Canada" },
  CV: { ar: "الرأس الأخضر", en: "Cape Verde" },
  CF: { ar: "جمهورية أفريقيا الوسطى", en: "Central African Republic" },
  TD: { ar: "تشاد", en: "Chad" },
  CL: { ar: "تشيلي", en: "Chile" },
  CN: { ar: "الصين", en: "China" },
  CO: { ar: "كولومبيا", en: "Colombia" },
  KM: { ar: "جزر القمر", en: "Comoros" },

  CG: { ar: "الكونغو", en: "Congo" },
  CD: { ar: "جمهورية الكونغو الديمقراطية", en: "DR Congo" },
  CR: { ar: "كوستاريكا", en: "Costa Rica" },
  HR: { ar: "كرواتيا", en: "Croatia" },
  CU: { ar: "كوبا", en: "Cuba" },
  CY: { ar: "قبرص", en: "Cyprus" },
  CZ: { ar: "التشيك", en: "Czechia" },

  DK: { ar: "الدنمارك", en: "Denmark" },
  DJ: { ar: "جيبوتي", en: "Djibouti" },
  DM: { ar: "دومينيكا", en: "Dominica" },
  DO: { ar: "جمهورية الدومينيكان", en: "Dominican Republic" },

  EC: { ar: "الإكوادور", en: "Ecuador" },
  EG: { ar: "مصر", en: "Egypt" },
  SV: { ar: "السلفادور", en: "El Salvador" },
  GQ: { ar: "غينيا الاستوائية", en: "Equatorial Guinea" },
  ER: { ar: "إريتريا", en: "Eritrea" },
  EE: { ar: "إستونيا", en: "Estonia" },
  SZ: { ar: "إسواتيني", en: "Eswatini" },
  ET: { ar: "إثيوبيا", en: "Ethiopia" },

  FI: { ar: "فنلندا", en: "Finland" },
  FR: { ar: "فرنسا", en: "France" },

  GA: { ar: "الغابون", en: "Gabon" },
  GM: { ar: "غامبيا", en: "Gambia" },
  GE: { ar: "جورجيا", en: "Georgia" },
  DE: { ar: "ألمانيا", en: "Germany" },
  GH: { ar: "غانا", en: "Ghana" },
  GR: { ar: "اليونان", en: "Greece" },
  GT: { ar: "غواتيمالا", en: "Guatemala" },
  GN: { ar: "غينيا", en: "Guinea" },
  GW: { ar: "غينيا بيساو", en: "Guinea-Bissau" },
  GY: { ar: "غيانا", en: "Guyana" },

  HT: { ar: "هايتي", en: "Haiti" },
  HN: { ar: "هندوراس", en: "Honduras" },
  HU: { ar: "المجر", en: "Hungary" },

  IS: { ar: "آيسلندا", en: "Iceland" },
  IN: { ar: "الهند", en: "India" },
  ID: { ar: "إندونيسيا", en: "Indonesia" },
  IR: { ar: "إيران", en: "Iran" },
  IQ: { ar: "العراق", en: "Iraq" },
  IE: { ar: "أيرلندا", en: "Ireland" },
  IL: { ar: "إسرائيل", en: "Israel" },
  IT: { ar: "إيطاليا", en: "Italy" },

  JM: { ar: "جامايكا", en: "Jamaica" },
  JP: { ar: "اليابان", en: "Japan" },
  JO: { ar: "الأردن", en: "Jordan" },

  KZ: { ar: "كازاخستان", en: "Kazakhstan" },
  KE: { ar: "كينيا", en: "Kenya" },
  KI: { ar: "كيريباتي", en: "Kiribati" },
  KR: { ar: "كوريا الجنوبية", en: "South Korea" },
  KW: { ar: "الكويت", en: "Kuwait" },
  KG: { ar: "قيرغيزستان", en: "Kyrgyzstan" },

  LA: { ar: "لاوس", en: "Laos" },
  LV: { ar: "لاتفيا", en: "Latvia" },
  LB: { ar: "لبنان", en: "Lebanon" },
  LS: { ar: "ليسوتو", en: "Lesotho" },
  LR: { ar: "ليبيريا", en: "Liberia" },
  LY: { ar: "ليبيا", en: "Libya" },
  LI: { ar: "ليختنشتاين", en: "Liechtenstein" },
  LT: { ar: "ليتوانيا", en: "Lithuania" },
  LU: { ar: "لوكسمبورغ", en: "Luxembourg" },

  MG: { ar: "مدغشقر", en: "Madagascar" },
  MW: { ar: "مالاوي", en: "Malawi" },
  MY: { ar: "ماليزيا", en: "Malaysia" },
  MV: { ar: "المالديف", en: "Maldives" },
  ML: { ar: "مالي", en: "Mali" },
  MT: { ar: "مالطا", en: "Malta" },
  MR: { ar: "موريتانيا", en: "Mauritania" },
  MU: { ar: "موريشيوس", en: "Mauritius" },
  MX: { ar: "المكسيك", en: "Mexico" },
  MD: { ar: "مولدوفا", en: "Moldova" },
  MC: { ar: "موناكو", en: "Monaco" },
  MN: { ar: "منغوليا", en: "Mongolia" },
  ME: { ar: "الجبل الأسود", en: "Montenegro" },
  MA: { ar: "المغرب", en: "Morocco" },
  MZ: { ar: "موزمبيق", en: "Mozambique" },

  MM: { ar: "ميانمار", en: "Myanmar" },
  NA: { ar: "ناميبيا", en: "Namibia" },
  NP: { ar: "نيبال", en: "Nepal" },
  NL: { ar: "هولندا", en: "Netherlands" },
  NZ: { ar: "نيوزيلندا", en: "New Zealand" },
  NI: { ar: "نيكاراغوا", en: "Nicaragua" },
  NE: { ar: "النيجر", en: "Niger" },
  NG: { ar: "نيجيريا", en: "Nigeria" },
  NO: { ar: "النرويج", en: "Norway" },

  OM: { ar: "عُمان", en: "Oman" },

  PK: { ar: "باكستان", en: "Pakistan" },
  PA: { ar: "بنما", en: "Panama" },
  PG: { ar: "بابوا غينيا الجديدة", en: "Papua New Guinea" },
  PY: { ar: "باراغواي", en: "Paraguay" },
  PE: { ar: "بيرو", en: "Peru" },
  PH: { ar: "الفلبين", en: "Philippines" },
  PL: { ar: "بولندا", en: "Poland" },
  PT: { ar: "البرتغال", en: "Portugal" },
  QA: { ar: "قطر", en: "Qatar" },
  PS: { ar: "فلسطين", en: "Palestine" },

  RO: { ar: "رومانيا", en: "Romania" },
  RU: { ar: "روسيا", en: "Russia" },
  RW: { ar: "رواندا", en: "Rwanda" },

  SA: { ar: "السعودية", en: "Saudi Arabia" },
  SN: { ar: "السنغال", en: "Senegal" },
  RS: { ar: "صربيا", en: "Serbia" },
  SC: { ar: "سيشل", en: "Seychelles" },
  SL: { ar: "سيراليون", en: "Sierra Leone" },
  SG: { ar: "سنغافورة", en: "Singapore" },
  SK: { ar: "سلوفاكيا", en: "Slovakia" },
  SI: { ar: "سلوفينيا", en: "Slovenia" },
  SB: { ar: "جزر سليمان", en: "Solomon Islands" },
  SO: { ar: "الصومال", en: "Somalia" },
  ZA: { ar: "جنوب أفريقيا", en: "South Africa" },
  ES: { ar: "إسبانيا", en: "Spain" },
  LK: { ar: "سريلانكا", en: "Sri Lanka" },
  SD: { ar: "السودان", en: "Sudan" },
  SE: { ar: "السويد", en: "Sweden" },
  CH: { ar: "سويسرا", en: "Switzerland" },
  SY: { ar: "سوريا", en: "Syria" },

  TW: { ar: "تايوان", en: "Taiwan" },
  TJ: { ar: "طاجيكستان", en: "Tajikistan" },
  TZ: { ar: "تنزانيا", en: "Tanzania" },
  TH: { ar: "تايلاند", en: "Thailand" },
  TL: { ar: "تيمور الشرقية", en: "Timor-Leste" },
  TG: { ar: "توغو", en: "Togo" },
  TO: { ar: "تونغا", en: "Tonga" },
  TT: { ar: "ترينيداد وتوباغو", en: "Trinidad and Tobago" },
  TN: { ar: "تونس", en: "Tunisia" },
  TR: { ar: "تركيا", en: "Turkey" },
  TM: { ar: "تركمانستان", en: "Turkmenistan" },

  UG: { ar: "أوغندا", en: "Uganda" },
  UA: { ar: "أوكرانيا", en: "Ukraine" },
  AE: { ar: "الإمارات", en: "United Arab Emirates" },
  GB: { ar: "المملكة المتحدة", en: "United Kingdom" },
  US: { ar: "الولايات المتحدة", en: "United States" },
  UY: { ar: "أوروغواي", en: "Uruguay" },
  UZ: { ar: "أوزبكستان", en: "Uzbekistan" },

  VE: { ar: "فنزويلا", en: "Venezuela" },
  VN: { ar: "فيتنام", en: "Vietnam" },

  YE: { ar: "اليمن", en: "Yemen" },

  ZM: { ar: "زامبيا", en: "Zambia" },
  ZW: { ar: "زيمبابوي", en: "Zimbabwe" },
};

export default countries;
